"""Hard-coded registered assets, contributors, users and check metadata for the demo."""

from __future__ import annotations

import hashlib

CLASSES = ["truck", "apc", "tank", "civilian_car", "pickup"]


def fake_digest(label: str) -> str:
    """Stable illustrative digest for a demo asset (the files themselves do not exist)."""
    return "sha256:" + hashlib.sha256(f"aura-demo::{label}".encode()).hexdigest()


CONTRIBUTORS = {
    "contributor_A": {"name": "Field Unit North", "kind": "unit"},
    "contributor_B": {"name": "Vendor Kestrel Imaging", "kind": "vendor"},
    "contributor_C": {"name": "Allied Source Delta", "kind": "allied"},
    "contributor_D": {"name": "Vendor Arcadia Labs", "kind": "vendor"},
    "contributor_E": {"name": "Field Unit West", "kind": "unit"},
}

REGISTERED_WEIGHT_DIGEST = fake_digest("vehnet-r18-v2.1.pt")

ASSETS: list[dict] = [
    {
        "id": "ds_vehicles_v3",
        "type": "dataset",
        "name": "UAV-Recon Vehicles v3",
        "format": "coco",
        "digest": fake_digest("ds_vehicles_v3"),
        "path": "data/uploads/uav_recon_vehicles_v3",
        "task": "classification",
        "class_names": CLASSES,
        "n_images": 4820,
        "n_annotations": 4820,
        "has_contributor_metadata": True,
        "contributors": list(CONTRIBUTORS),
        "validation_summary": {"format_detected": "coco", "sanity_issues": 3, "contributors": 5, "batches": 14},
        "registered_by": "admin",
    },
    {
        "id": "ds_vehicles_v2",
        "type": "dataset",
        "name": "UAV-Recon Vehicles v2 (trusted baseline)",
        "format": "yolo",
        "digest": fake_digest("ds_vehicles_v2"),
        "path": "data/uploads/uav_recon_vehicles_v2",
        "task": "classification",
        "class_names": CLASSES,
        "n_images": 3100,
        "n_annotations": 3100,
        "has_contributor_metadata": True,
        "contributors": ["contributor_A", "contributor_E"],
        "validation_summary": {"format_detected": "yolo", "sanity_issues": 0, "contributors": 2, "batches": 6},
        "registered_by": "admin",
    },
    {
        "id": "ds_vehicles_nometa",
        "type": "dataset",
        "name": "Vendor drop 17 (no source metadata)",
        "format": "imagefolder",
        "digest": fake_digest("ds_vehicles_nometa"),
        "path": "data/uploads/vendor_drop_17",
        "task": "classification",
        "class_names": CLASSES,
        "n_images": 1260,
        "n_annotations": 1260,
        "has_contributor_metadata": False,
        "contributors": [],
        "validation_summary": {"format_detected": "imagefolder", "sanity_issues": 0, "contributors": 0, "batches": 0},
        "registered_by": "analyst",
    },
    {
        "id": "mdl_vehnet_v21",
        "type": "model",
        "name": "VehNet-R18 v2.1 (TorchScript)",
        "format": "torchscript",
        "digest": REGISTERED_WEIGHT_DIGEST,
        "weight_digest": REGISTERED_WEIGHT_DIGEST,
        "registered_digest": REGISTERED_WEIGHT_DIGEST,
        "structure_digest": fake_digest("vehnet-structure"),
        "path": "data/uploads/vehnet_r18_v21.pt",
        "task": "classification",
        "class_names": CLASSES,
        "detected_access_level": "WB",
        "supplier": "Vendor Kestrel Imaging",
        "claimed_accuracy": 0.940,
        "input_spec": {"shape": [1, 3, 224, 224], "dtype": "float32"},
        "registered_by": "admin",
    },
    {
        "id": "mdl_vehnet_v21_onnx",
        "type": "model",
        "name": "VehNet-R18 v2.1 (ONNX export, scores only)",
        "format": "onnx",
        "digest": fake_digest("vehnet-r18-v2.1.onnx"),
        "weight_digest": fake_digest("vehnet-r18-v2.1.onnx"),
        "registered_digest": fake_digest("vehnet-r18-v2.1.onnx"),
        "structure_digest": None,
        "path": "data/uploads/vehnet_r18_v21.onnx",
        "task": "classification",
        "class_names": CLASSES,
        "detected_access_level": "BB-S",
        "supplier": "Vendor Kestrel Imaging",
        "claimed_accuracy": 0.940,
        "input_spec": {"shape": [1, 3, 224, 224], "dtype": "float32"},
        "registered_by": "admin",
    },
    {
        "id": "mdl_vehnet_v22",
        "type": "model",
        "name": "VehNet-R18 v2.2 (supplier update)",
        "format": "torchscript",
        "digest": fake_digest("vehnet-r18-v2.2.pt"),
        "weight_digest": fake_digest("vehnet-r18-v2.2.pt"),
        "registered_digest": REGISTERED_WEIGHT_DIGEST,
        "structure_digest": fake_digest("vehnet-structure-v22"),
        "path": "data/uploads/vehnet_r18_v22.pt",
        "task": "classification",
        "class_names": CLASSES,
        "detected_access_level": "WB",
        "supplier": "Vendor Kestrel Imaging",
        "claimed_accuracy": 0.951,
        "input_spec": {"shape": [1, 3, 224, 224], "dtype": "float32"},
        "registered_by": "analyst",
    },
    {
        "id": "rs_uav07_front",
        "type": "record_stream",
        "name": "UAV-07 front camera · patrol 14 Sep",
        "format": "jsonl",
        "stream_id": "uav-07-cam-front",
        "path": "data/uploads/uav07_front_records.jsonl",
        "registered_by": "analyst",
    },
    {
        "id": "ib_sector7_dawn",
        "type": "input_batch",
        "name": "Sector-7 dawn patrol",
        "format": "imagefolder",
        "digest": fake_digest("ib_sector7_dawn"),
        "path": "data/uploads/sector7_dawn",
        "n_images": 380,
        "acquisition_metadata": {"time_of_day": "05:40-06:25", "sensor": "EO-2 gimbal", "weather": "light haze"},
        "registered_by": "analyst",
    },
    {
        "id": "ib_sector9_relay",
        "type": "input_batch",
        "name": "Sector-9 relay feed",
        "format": "imagefolder",
        "digest": fake_digest("ib_sector9_relay"),
        "path": "data/uploads/sector9_relay",
        "n_images": 210,
        "acquisition_metadata": {},
        "registered_by": "analyst",
    },
    {
        "id": "ref_plains_summer",
        "type": "reference",
        "name": "Northern plains · summer daylight",
        "format": "imagefolder",
        "digest": fake_digest("ref_plains_summer"),
        "path": "assets/reference/plains_summer",
        "n_images": 2400,
        "embedding_digest": fake_digest("ref-embeddings"),
        "descriptor_digest": fake_digest("ref-descriptors"),
        "calibration_set_digest": fake_digest("ref-calibration"),
        "is_default": True,
        "registered_by": "admin",
    },
]

BATTERY = {
    "version": "battery-2026.09-r3",
    "digest": fake_digest("battery-2026.09-r3"),
    "clean_per_class": 60,
    "variants": ["brightness ±30%", "gaussian blur σ=1.5", "sensor noise σ=0.03", "JPEG q=40"],
    "probe_patches": 24,
    "built_from": "ref_plains_summer",
}

# Demo login accounts (shown on the login screen of the demo build).
USERS = [
    {"id": "usr_admin", "username": "admin", "password": "aura-admin", "role": "ADMIN", "display": "Maj. R. Iyer (Admin)"},
    {"id": "usr_analyst", "username": "analyst", "password": "aura-analyst", "role": "ANALYST", "display": "Capt. S. Menon (Analyst)"},
]

# check_id -> (short name, what it looks for, requirement id)
CHECK_META: dict[str, tuple[str, str, str]] = {
    "M1.annot.sanity": ("Annotation sanity", "Unreadable files, invalid class ids, bad boxes", "R-CON-2"),
    "M1.trigger.patch_repeat": ("Repeated patch trigger", "Identical small patches recurring within one label", "R-DATA-1"),
    "M1.trigger.hf_residual": ("High-frequency residue", "Localised, consistent residue after blurring", "R-DATA-1"),
    "M1.trigger.activation_cluster": ("Activation clustering", "Small, well-separated embedding cluster inside a class", "R-DATA-1"),
    "M1.trigger.spectral": ("Spectral signature", "Outliers on the top singular direction per class", "R-DATA-1"),
    "M1.flip.knn": ("Neighbour label consensus", "Given label disagrees with nearest neighbours", "R-DATA-2"),
    "M1.flip.confident": ("Confident-learning flips", "Out-of-sample classifier confidently disagrees", "R-DATA-2"),
    "M1.systematic.confusion": ("Systematic relabelling", "One contributor maps class X to class Y", "R-DATA-3"),
    "M1.dup.phash": ("Perceptual-hash duplicates", "Near-identical images by pHash distance", "R-DATA-4"),
    "M1.dup.embed": ("Embedding duplicates", "Near-identical images by embedding similarity", "R-DATA-4"),
    "M1.ood.knn": ("k-NN novelty", "Samples far from the reference distribution", "R-DATA-5"),
    "M1.ood.mahalanobis": ("Class-conditional OOD", "Samples outside their class Gaussian", "R-DATA-5"),
    "M1.source_risk": ("Source-level risk", "Beta-Binomial risk per contributor / batch", "R-DATA-6"),
    "M2.digest": ("Weight digest", "SHA-256 of weights vs registered digest", "R-MOD-1"),
    "M2.structure": ("Graph structure", "Layer graph digest vs registered", "R-MOD-1"),
    "M2.fingerprint": ("Behavioural fingerprint", "Agreement with registered battery fingerprint", "R-MOD-2"),
    "M2.reference_accuracy": ("Reference accuracy", "Clean battery accuracy vs supplier claim", "R-MOD-1"),
    "M2.trigger_reconstruction": ("Trigger reconstruction", "Neural-Cleanse style mask + pattern search", "R-MOD-2"),
    "M2.activation_stats": ("Dormant-neuron activation", "Neurons silent on clean data, active on triggers", "R-MOD-2"),
    "M2.param_stats": ("Weight statistics", "Per-layer kurtosis / skew vs reference", "R-MOD-2"),
    "M2.strip": ("STRIP entropy", "Low-entropy persistence under superimposition", "R-MOD-1"),
    "M2.patch_probe": ("Patch probing", "Flip rate towards one class when patches are pasted", "R-MOD-1"),
    "M3.record_verification": ("Record verification", "Signature, chain, sequence, nonce, time, digests", "R-INF-2"),
    "M4.mmd": ("Embedding MMD test", "Kernel two-sample test vs declared reference", "R-SHIFT-1"),
    "M4.descriptors": ("Descriptor shift", "Luminance, contrast, colour, sharpness, noise, spectrum", "R-SHIFT-2"),
    "M4.output_shift": ("Model output shift", "Class frequency and confidence drift", "R-SHIFT-1"),
    "M4.calibration": ("Calibrated risk", "Isotonic map from shift features to harm probability", "R-SHIFT-3"),
    "M4.verdict": ("Drift vs manipulation", "Evidence rules engine with INCONCLUSIVE outcome", "R-SHIFT-4"),
    "M4.metadata_consistency": ("Metadata consistency", "Shift pattern vs supplied acquisition metadata", "R-SHIFT-4"),
}
